# Generated by Django 4.2.1 on 2024-08-29 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0002_meeting_google_calendar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
